name: Build Binary
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Build Program
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
    - run: | 
        GOARCH=amd64 GOOS=linux go build -o latest.elf main.go

    # Create Release
    - uses: actions/create-release@v1
      id: release_create
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - uses: actions/upload-release-asset@v1
      id: release_upload
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_create.outputs.upload_url }}
        asset_path: ./latest.elf
        asset_name: latest.elf
        asset_content_type: application/octet-stream